# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('affix', models.TextField(blank=True, null=True)),
                ('character_type', models.CharField(choices=[('All', 'All'), ('Barbarian', 'Barbarian'), ('Crusader', 'Crusader'), ('Demon Hunter', 'Demon Hunter'), ('Monk', 'Monk'), ('Witch Doctor', 'Witch Doctor'), ('Wizard', 'Wizard')], max_length=50)),
                ('cube_slot', models.CharField(choices=[('Weapon', 'Weapon'), ('Armor', 'Armor'), ('Jewelry', 'Jewelry')], max_length=50)),
            ],
        ),
    ]
