# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cube',
            name='in_cube',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cube',
            name='in_stash',
            field=models.BooleanField(default=False),
        ),
    ]
