# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactertype',
            name='short_name',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cube',
            name='character_type',
            field=models.ManyToManyField(blank=True, to='cube.CharacterType'),
        ),
    ]
