# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Cube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('affix', models.TextField(blank=True, null=True)),
                ('in_cube', models.BooleanField(default=False)),
                ('in_stash', models.BooleanField(default=False)),
                ('character_type', models.ManyToManyField(blank=True, null=True, to='cube.CharacterType')),
            ],
        ),
        migrations.CreateModel(
            name='CubeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='cube',
            name='cube_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cube.CubeType'),
        ),
    ]
